project:
  type: website
  output-dir: docs

website:
  title: "LS 빅데이터 스쿨 Qmd 블로그 실습"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/osangwon/sangwon-blog
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



